namespace GaborTransformExample
{
    partial class FormGaborTransformExample
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            SeeSharpTools.JY.GUI.EasyChartXSeries easyChartXSeries1 = new SeeSharpTools.JY.GUI.EasyChartXSeries();
            SeeSharpTools.JY.GUI.EasyChartXSeries easyChartXSeries2 = new SeeSharpTools.JY.GUI.EasyChartXSeries();
            SeeSharpTools.JY.GUI.EasyChartXSeries easyChartXSeries3 = new SeeSharpTools.JY.GUI.EasyChartXSeries();
            SeeSharpTools.JY.GUI.EasyChartXSeries easyChartXSeries4 = new SeeSharpTools.JY.GUI.EasyChartXSeries();
            this.easyChartXInputWaveform = new SeeSharpTools.JY.GUI.EasyChartX();
            this.easyChartXInputTFWaterfall = new SeeSharpTools.JY.GUI.EasyChartX();
            this.easyChartXFilteredTFWaterfall = new SeeSharpTools.JY.GUI.EasyChartX();
            this.easyChartXFilteredWaveform = new SeeSharpTools.JY.GUI.EasyChartX();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.radioButtonHalfSpectrum = new System.Windows.Forms.RadioButton();
            this.radioButtonFullSpectrum = new System.Windows.Forms.RadioButton();
            this.easyButtonGo = new SeeSharpTools.JY.GUI.EasyButton();
            this.numericUpDownNoiseRMS = new System.Windows.Forms.NumericUpDown();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownNoiseRMS)).BeginInit();
            this.SuspendLayout();
            // 
            // easyChartXInputWaveform
            // 
            this.easyChartXInputWaveform.AutoClear = true;
            this.easyChartXInputWaveform.AxisX.AutoScale = true;
            this.easyChartXInputWaveform.AxisX.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputWaveform.AxisX.AutoZoomReset = false;
            this.easyChartXInputWaveform.AxisX.Color = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisX.InitWithScaleView = false;
            this.easyChartXInputWaveform.AxisX.IsLogarithmic = false;
            this.easyChartXInputWaveform.AxisX.LabelAngle = 0;
            this.easyChartXInputWaveform.AxisX.LabelEnabled = true;
            this.easyChartXInputWaveform.AxisX.LabelFormat = null;
            this.easyChartXInputWaveform.AxisX.LogarithmBase = 10D;
            this.easyChartXInputWaveform.AxisX.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputWaveform.AxisX.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisX.MajorGridCount = -1;
            this.easyChartXInputWaveform.AxisX.MajorGridEnabled = true;
            this.easyChartXInputWaveform.AxisX.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputWaveform.AxisX.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputWaveform.AxisX.Maximum = 1000D;
            this.easyChartXInputWaveform.AxisX.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputWaveform.AxisX.Minimum = 0D;
            this.easyChartXInputWaveform.AxisX.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputWaveform.AxisX.MinorGridEnabled = false;
            this.easyChartXInputWaveform.AxisX.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputWaveform.AxisX.ShowLogarithmicLines = false;
            this.easyChartXInputWaveform.AxisX.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisX.TickWidth = 1F;
            this.easyChartXInputWaveform.AxisX.Title = "";
            this.easyChartXInputWaveform.AxisX.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputWaveform.AxisX.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputWaveform.AxisX.ViewMaximum = 1000D;
            this.easyChartXInputWaveform.AxisX.ViewMinimum = 0D;
            this.easyChartXInputWaveform.AxisX2.AutoScale = true;
            this.easyChartXInputWaveform.AxisX2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputWaveform.AxisX2.AutoZoomReset = false;
            this.easyChartXInputWaveform.AxisX2.Color = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisX2.InitWithScaleView = false;
            this.easyChartXInputWaveform.AxisX2.IsLogarithmic = false;
            this.easyChartXInputWaveform.AxisX2.LabelAngle = 0;
            this.easyChartXInputWaveform.AxisX2.LabelEnabled = true;
            this.easyChartXInputWaveform.AxisX2.LabelFormat = null;
            this.easyChartXInputWaveform.AxisX2.LogarithmBase = 10D;
            this.easyChartXInputWaveform.AxisX2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputWaveform.AxisX2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisX2.MajorGridCount = -1;
            this.easyChartXInputWaveform.AxisX2.MajorGridEnabled = true;
            this.easyChartXInputWaveform.AxisX2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputWaveform.AxisX2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputWaveform.AxisX2.Maximum = 1000D;
            this.easyChartXInputWaveform.AxisX2.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputWaveform.AxisX2.Minimum = 0D;
            this.easyChartXInputWaveform.AxisX2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputWaveform.AxisX2.MinorGridEnabled = false;
            this.easyChartXInputWaveform.AxisX2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputWaveform.AxisX2.ShowLogarithmicLines = false;
            this.easyChartXInputWaveform.AxisX2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisX2.TickWidth = 1F;
            this.easyChartXInputWaveform.AxisX2.Title = "";
            this.easyChartXInputWaveform.AxisX2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputWaveform.AxisX2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputWaveform.AxisX2.ViewMaximum = 1000D;
            this.easyChartXInputWaveform.AxisX2.ViewMinimum = 0D;
            this.easyChartXInputWaveform.AxisY.AutoScale = false;
            this.easyChartXInputWaveform.AxisY.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputWaveform.AxisY.AutoZoomReset = false;
            this.easyChartXInputWaveform.AxisY.Color = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisY.InitWithScaleView = false;
            this.easyChartXInputWaveform.AxisY.IsLogarithmic = false;
            this.easyChartXInputWaveform.AxisY.LabelAngle = 0;
            this.easyChartXInputWaveform.AxisY.LabelEnabled = true;
            this.easyChartXInputWaveform.AxisY.LabelFormat = null;
            this.easyChartXInputWaveform.AxisY.LogarithmBase = 10D;
            this.easyChartXInputWaveform.AxisY.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputWaveform.AxisY.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisY.MajorGridCount = 6;
            this.easyChartXInputWaveform.AxisY.MajorGridEnabled = true;
            this.easyChartXInputWaveform.AxisY.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputWaveform.AxisY.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputWaveform.AxisY.Maximum = 3.5D;
            this.easyChartXInputWaveform.AxisY.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputWaveform.AxisY.Minimum = -3.5D;
            this.easyChartXInputWaveform.AxisY.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputWaveform.AxisY.MinorGridEnabled = false;
            this.easyChartXInputWaveform.AxisY.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputWaveform.AxisY.ShowLogarithmicLines = false;
            this.easyChartXInputWaveform.AxisY.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisY.TickWidth = 1F;
            this.easyChartXInputWaveform.AxisY.Title = "";
            this.easyChartXInputWaveform.AxisY.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputWaveform.AxisY.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputWaveform.AxisY.ViewMaximum = 3.5D;
            this.easyChartXInputWaveform.AxisY.ViewMinimum = 0.5D;
            this.easyChartXInputWaveform.AxisY2.AutoScale = true;
            this.easyChartXInputWaveform.AxisY2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputWaveform.AxisY2.AutoZoomReset = false;
            this.easyChartXInputWaveform.AxisY2.Color = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisY2.InitWithScaleView = false;
            this.easyChartXInputWaveform.AxisY2.IsLogarithmic = false;
            this.easyChartXInputWaveform.AxisY2.LabelAngle = 0;
            this.easyChartXInputWaveform.AxisY2.LabelEnabled = true;
            this.easyChartXInputWaveform.AxisY2.LabelFormat = null;
            this.easyChartXInputWaveform.AxisY2.LogarithmBase = 10D;
            this.easyChartXInputWaveform.AxisY2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputWaveform.AxisY2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisY2.MajorGridCount = 6;
            this.easyChartXInputWaveform.AxisY2.MajorGridEnabled = true;
            this.easyChartXInputWaveform.AxisY2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputWaveform.AxisY2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputWaveform.AxisY2.Maximum = 3.5D;
            this.easyChartXInputWaveform.AxisY2.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputWaveform.AxisY2.Minimum = 0.5D;
            this.easyChartXInputWaveform.AxisY2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputWaveform.AxisY2.MinorGridEnabled = false;
            this.easyChartXInputWaveform.AxisY2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputWaveform.AxisY2.ShowLogarithmicLines = false;
            this.easyChartXInputWaveform.AxisY2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.AxisY2.TickWidth = 1F;
            this.easyChartXInputWaveform.AxisY2.Title = "";
            this.easyChartXInputWaveform.AxisY2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputWaveform.AxisY2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputWaveform.AxisY2.ViewMaximum = 3.5D;
            this.easyChartXInputWaveform.AxisY2.ViewMinimum = 0.5D;
            this.easyChartXInputWaveform.BackColor = System.Drawing.Color.White;
            this.easyChartXInputWaveform.ChartAreaBackColor = System.Drawing.Color.Empty;
            this.easyChartXInputWaveform.Cumulitive = false;
            this.easyChartXInputWaveform.GradientStyle = SeeSharpTools.JY.GUI.EasyChartX.ChartGradientStyle.None;
            this.easyChartXInputWaveform.LegendBackColor = System.Drawing.Color.Transparent;
            this.easyChartXInputWaveform.LegendFont = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            this.easyChartXInputWaveform.LegendForeColor = System.Drawing.Color.Black;
            this.easyChartXInputWaveform.LegendVisible = false;
            easyChartXSeries1.Color = System.Drawing.Color.Red;
            easyChartXSeries1.Marker = SeeSharpTools.JY.GUI.EasyChartXSeries.MarkerType.None;
            easyChartXSeries1.Name = "Series1";
            easyChartXSeries1.Type = SeeSharpTools.JY.GUI.EasyChartXSeries.LineType.FastLine;
            easyChartXSeries1.Visible = true;
            easyChartXSeries1.Width = SeeSharpTools.JY.GUI.EasyChartXSeries.LineWidth.Thin;
            easyChartXSeries1.XPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            easyChartXSeries1.YPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            this.easyChartXInputWaveform.LineSeries.Add(easyChartXSeries1);
            this.easyChartXInputWaveform.Location = new System.Drawing.Point(1, 18);
            this.easyChartXInputWaveform.Miscellaneous.CheckInfinity = false;
            this.easyChartXInputWaveform.Miscellaneous.CheckNaN = false;
            this.easyChartXInputWaveform.Miscellaneous.CheckNegtiveOrZero = false;
            this.easyChartXInputWaveform.Miscellaneous.DataStorage = SeeSharpTools.JY.GUI.DataStorageType.Clone;
            this.easyChartXInputWaveform.Miscellaneous.DirectionChartCount = 3;
            this.easyChartXInputWaveform.Miscellaneous.Fitting = SeeSharpTools.JY.GUI.EasyChartX.FitType.Range;
            this.easyChartXInputWaveform.Miscellaneous.MarkerSize = 7;
            this.easyChartXInputWaveform.Miscellaneous.MaxSeriesCount = 32;
            this.easyChartXInputWaveform.Miscellaneous.MaxSeriesPointCount = 4000;
            this.easyChartXInputWaveform.Miscellaneous.ShowFunctionMenu = true;
            this.easyChartXInputWaveform.Miscellaneous.SplitLayoutColumnInterval = 0F;
            this.easyChartXInputWaveform.Miscellaneous.SplitLayoutDirection = SeeSharpTools.JY.GUI.EasyChartXUtility.LayoutDirection.LeftToRight;
            this.easyChartXInputWaveform.Miscellaneous.SplitLayoutRowInterval = 0F;
            this.easyChartXInputWaveform.Miscellaneous.SplitViewAutoLayout = true;
            this.easyChartXInputWaveform.Name = "easyChartXInputWaveform";
            this.easyChartXInputWaveform.SeriesCount = 0;
            this.easyChartXInputWaveform.Size = new System.Drawing.Size(352, 178);
            this.easyChartXInputWaveform.SplitView = false;
            this.easyChartXInputWaveform.TabIndex = 0;
            this.easyChartXInputWaveform.XCursor.AutoInterval = true;
            this.easyChartXInputWaveform.XCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXInputWaveform.XCursor.Interval = 0.001D;
            this.easyChartXInputWaveform.XCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Zoom;
            this.easyChartXInputWaveform.XCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXInputWaveform.XCursor.Value = double.NaN;
            this.easyChartXInputWaveform.YCursor.AutoInterval = true;
            this.easyChartXInputWaveform.YCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXInputWaveform.YCursor.Interval = 0.001D;
            this.easyChartXInputWaveform.YCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Disabled;
            this.easyChartXInputWaveform.YCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXInputWaveform.YCursor.Value = double.NaN;
            // 
            // easyChartXInputTFWaterfall
            // 
            this.easyChartXInputTFWaterfall.AutoClear = true;
            this.easyChartXInputTFWaterfall.AxisX.AutoScale = true;
            this.easyChartXInputTFWaterfall.AxisX.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputTFWaterfall.AxisX.AutoZoomReset = false;
            this.easyChartXInputTFWaterfall.AxisX.Color = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisX.InitWithScaleView = false;
            this.easyChartXInputTFWaterfall.AxisX.IsLogarithmic = false;
            this.easyChartXInputTFWaterfall.AxisX.LabelAngle = 0;
            this.easyChartXInputTFWaterfall.AxisX.LabelEnabled = false;
            this.easyChartXInputTFWaterfall.AxisX.LabelFormat = null;
            this.easyChartXInputTFWaterfall.AxisX.LogarithmBase = 10D;
            this.easyChartXInputTFWaterfall.AxisX.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputTFWaterfall.AxisX.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisX.MajorGridCount = -1;
            this.easyChartXInputTFWaterfall.AxisX.MajorGridEnabled = true;
            this.easyChartXInputTFWaterfall.AxisX.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputTFWaterfall.AxisX.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputTFWaterfall.AxisX.Maximum = 1000D;
            this.easyChartXInputTFWaterfall.AxisX.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputTFWaterfall.AxisX.Minimum = 1D;
            this.easyChartXInputTFWaterfall.AxisX.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputTFWaterfall.AxisX.MinorGridEnabled = false;
            this.easyChartXInputTFWaterfall.AxisX.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputTFWaterfall.AxisX.ShowLogarithmicLines = false;
            this.easyChartXInputTFWaterfall.AxisX.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisX.TickWidth = 1F;
            this.easyChartXInputTFWaterfall.AxisX.Title = "";
            this.easyChartXInputTFWaterfall.AxisX.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputTFWaterfall.AxisX.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputTFWaterfall.AxisX.ViewMaximum = 1000D;
            this.easyChartXInputTFWaterfall.AxisX.ViewMinimum = 0D;
            this.easyChartXInputTFWaterfall.AxisX2.AutoScale = true;
            this.easyChartXInputTFWaterfall.AxisX2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputTFWaterfall.AxisX2.AutoZoomReset = false;
            this.easyChartXInputTFWaterfall.AxisX2.Color = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisX2.InitWithScaleView = false;
            this.easyChartXInputTFWaterfall.AxisX2.IsLogarithmic = false;
            this.easyChartXInputTFWaterfall.AxisX2.LabelAngle = 0;
            this.easyChartXInputTFWaterfall.AxisX2.LabelEnabled = false;
            this.easyChartXInputTFWaterfall.AxisX2.LabelFormat = null;
            this.easyChartXInputTFWaterfall.AxisX2.LogarithmBase = 10D;
            this.easyChartXInputTFWaterfall.AxisX2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputTFWaterfall.AxisX2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisX2.MajorGridCount = -1;
            this.easyChartXInputTFWaterfall.AxisX2.MajorGridEnabled = true;
            this.easyChartXInputTFWaterfall.AxisX2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputTFWaterfall.AxisX2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputTFWaterfall.AxisX2.Maximum = 1000D;
            this.easyChartXInputTFWaterfall.AxisX2.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputTFWaterfall.AxisX2.Minimum = 0D;
            this.easyChartXInputTFWaterfall.AxisX2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputTFWaterfall.AxisX2.MinorGridEnabled = false;
            this.easyChartXInputTFWaterfall.AxisX2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputTFWaterfall.AxisX2.ShowLogarithmicLines = false;
            this.easyChartXInputTFWaterfall.AxisX2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisX2.TickWidth = 1F;
            this.easyChartXInputTFWaterfall.AxisX2.Title = "";
            this.easyChartXInputTFWaterfall.AxisX2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputTFWaterfall.AxisX2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputTFWaterfall.AxisX2.ViewMaximum = 1000D;
            this.easyChartXInputTFWaterfall.AxisX2.ViewMinimum = 0D;
            this.easyChartXInputTFWaterfall.AxisY.AutoScale = true;
            this.easyChartXInputTFWaterfall.AxisY.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputTFWaterfall.AxisY.AutoZoomReset = false;
            this.easyChartXInputTFWaterfall.AxisY.Color = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisY.InitWithScaleView = false;
            this.easyChartXInputTFWaterfall.AxisY.IsLogarithmic = false;
            this.easyChartXInputTFWaterfall.AxisY.LabelAngle = 0;
            this.easyChartXInputTFWaterfall.AxisY.LabelEnabled = false;
            this.easyChartXInputTFWaterfall.AxisY.LabelFormat = null;
            this.easyChartXInputTFWaterfall.AxisY.LogarithmBase = 10D;
            this.easyChartXInputTFWaterfall.AxisY.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputTFWaterfall.AxisY.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisY.MajorGridCount = 6;
            this.easyChartXInputTFWaterfall.AxisY.MajorGridEnabled = true;
            this.easyChartXInputTFWaterfall.AxisY.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputTFWaterfall.AxisY.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputTFWaterfall.AxisY.Maximum = 3.5D;
            this.easyChartXInputTFWaterfall.AxisY.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputTFWaterfall.AxisY.Minimum = 0.5D;
            this.easyChartXInputTFWaterfall.AxisY.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputTFWaterfall.AxisY.MinorGridEnabled = false;
            this.easyChartXInputTFWaterfall.AxisY.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputTFWaterfall.AxisY.ShowLogarithmicLines = false;
            this.easyChartXInputTFWaterfall.AxisY.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisY.TickWidth = 1F;
            this.easyChartXInputTFWaterfall.AxisY.Title = "";
            this.easyChartXInputTFWaterfall.AxisY.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputTFWaterfall.AxisY.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputTFWaterfall.AxisY.ViewMaximum = 3.5D;
            this.easyChartXInputTFWaterfall.AxisY.ViewMinimum = 0.5D;
            this.easyChartXInputTFWaterfall.AxisY2.AutoScale = true;
            this.easyChartXInputTFWaterfall.AxisY2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXInputTFWaterfall.AxisY2.AutoZoomReset = false;
            this.easyChartXInputTFWaterfall.AxisY2.Color = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisY2.InitWithScaleView = false;
            this.easyChartXInputTFWaterfall.AxisY2.IsLogarithmic = false;
            this.easyChartXInputTFWaterfall.AxisY2.LabelAngle = 0;
            this.easyChartXInputTFWaterfall.AxisY2.LabelEnabled = false;
            this.easyChartXInputTFWaterfall.AxisY2.LabelFormat = null;
            this.easyChartXInputTFWaterfall.AxisY2.LogarithmBase = 10D;
            this.easyChartXInputTFWaterfall.AxisY2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXInputTFWaterfall.AxisY2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisY2.MajorGridCount = 6;
            this.easyChartXInputTFWaterfall.AxisY2.MajorGridEnabled = true;
            this.easyChartXInputTFWaterfall.AxisY2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXInputTFWaterfall.AxisY2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXInputTFWaterfall.AxisY2.Maximum = 3.5D;
            this.easyChartXInputTFWaterfall.AxisY2.MinGridCountPerPixel = 0.004D;
            this.easyChartXInputTFWaterfall.AxisY2.Minimum = 0.5D;
            this.easyChartXInputTFWaterfall.AxisY2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXInputTFWaterfall.AxisY2.MinorGridEnabled = false;
            this.easyChartXInputTFWaterfall.AxisY2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXInputTFWaterfall.AxisY2.ShowLogarithmicLines = false;
            this.easyChartXInputTFWaterfall.AxisY2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.AxisY2.TickWidth = 1F;
            this.easyChartXInputTFWaterfall.AxisY2.Title = "";
            this.easyChartXInputTFWaterfall.AxisY2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXInputTFWaterfall.AxisY2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXInputTFWaterfall.AxisY2.ViewMaximum = 3.5D;
            this.easyChartXInputTFWaterfall.AxisY2.ViewMinimum = 0.5D;
            this.easyChartXInputTFWaterfall.BackColor = System.Drawing.Color.White;
            this.easyChartXInputTFWaterfall.ChartAreaBackColor = System.Drawing.Color.Empty;
            this.easyChartXInputTFWaterfall.Cumulitive = false;
            this.easyChartXInputTFWaterfall.GradientStyle = SeeSharpTools.JY.GUI.EasyChartX.ChartGradientStyle.None;
            this.easyChartXInputTFWaterfall.LegendBackColor = System.Drawing.Color.Transparent;
            this.easyChartXInputTFWaterfall.LegendFont = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            this.easyChartXInputTFWaterfall.LegendForeColor = System.Drawing.Color.Black;
            this.easyChartXInputTFWaterfall.LegendVisible = false;
            easyChartXSeries2.Color = System.Drawing.Color.Red;
            easyChartXSeries2.Marker = SeeSharpTools.JY.GUI.EasyChartXSeries.MarkerType.None;
            easyChartXSeries2.Name = "Series1";
            easyChartXSeries2.Type = SeeSharpTools.JY.GUI.EasyChartXSeries.LineType.FastLine;
            easyChartXSeries2.Visible = true;
            easyChartXSeries2.Width = SeeSharpTools.JY.GUI.EasyChartXSeries.LineWidth.Thin;
            easyChartXSeries2.XPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            easyChartXSeries2.YPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            this.easyChartXInputTFWaterfall.LineSeries.Add(easyChartXSeries2);
            this.easyChartXInputTFWaterfall.Location = new System.Drawing.Point(352, 18);
            this.easyChartXInputTFWaterfall.Miscellaneous.CheckInfinity = false;
            this.easyChartXInputTFWaterfall.Miscellaneous.CheckNaN = false;
            this.easyChartXInputTFWaterfall.Miscellaneous.CheckNegtiveOrZero = false;
            this.easyChartXInputTFWaterfall.Miscellaneous.DataStorage = SeeSharpTools.JY.GUI.DataStorageType.Clone;
            this.easyChartXInputTFWaterfall.Miscellaneous.DirectionChartCount = 3;
            this.easyChartXInputTFWaterfall.Miscellaneous.Fitting = SeeSharpTools.JY.GUI.EasyChartX.FitType.Range;
            this.easyChartXInputTFWaterfall.Miscellaneous.MarkerSize = 7;
            this.easyChartXInputTFWaterfall.Miscellaneous.MaxSeriesCount = 32;
            this.easyChartXInputTFWaterfall.Miscellaneous.MaxSeriesPointCount = 4000;
            this.easyChartXInputTFWaterfall.Miscellaneous.ShowFunctionMenu = true;
            this.easyChartXInputTFWaterfall.Miscellaneous.SplitLayoutColumnInterval = 0F;
            this.easyChartXInputTFWaterfall.Miscellaneous.SplitLayoutDirection = SeeSharpTools.JY.GUI.EasyChartXUtility.LayoutDirection.LeftToRight;
            this.easyChartXInputTFWaterfall.Miscellaneous.SplitLayoutRowInterval = 0F;
            this.easyChartXInputTFWaterfall.Miscellaneous.SplitViewAutoLayout = true;
            this.easyChartXInputTFWaterfall.Name = "easyChartXInputTFWaterfall";
            this.easyChartXInputTFWaterfall.SeriesCount = 0;
            this.easyChartXInputTFWaterfall.Size = new System.Drawing.Size(352, 178);
            this.easyChartXInputTFWaterfall.SplitView = false;
            this.easyChartXInputTFWaterfall.TabIndex = 1;
            this.easyChartXInputTFWaterfall.XCursor.AutoInterval = true;
            this.easyChartXInputTFWaterfall.XCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXInputTFWaterfall.XCursor.Interval = 0.001D;
            this.easyChartXInputTFWaterfall.XCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Zoom;
            this.easyChartXInputTFWaterfall.XCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXInputTFWaterfall.XCursor.Value = double.NaN;
            this.easyChartXInputTFWaterfall.YCursor.AutoInterval = true;
            this.easyChartXInputTFWaterfall.YCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXInputTFWaterfall.YCursor.Interval = 0.001D;
            this.easyChartXInputTFWaterfall.YCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Disabled;
            this.easyChartXInputTFWaterfall.YCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXInputTFWaterfall.YCursor.Value = double.NaN;
            // 
            // easyChartXFilteredTFWaterfall
            // 
            this.easyChartXFilteredTFWaterfall.AutoClear = true;
            this.easyChartXFilteredTFWaterfall.AxisX.AutoScale = true;
            this.easyChartXFilteredTFWaterfall.AxisX.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredTFWaterfall.AxisX.AutoZoomReset = false;
            this.easyChartXFilteredTFWaterfall.AxisX.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisX.InitWithScaleView = false;
            this.easyChartXFilteredTFWaterfall.AxisX.IsLogarithmic = false;
            this.easyChartXFilteredTFWaterfall.AxisX.LabelAngle = 0;
            this.easyChartXFilteredTFWaterfall.AxisX.LabelEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisX.LabelFormat = null;
            this.easyChartXFilteredTFWaterfall.AxisX.LogarithmBase = 10D;
            this.easyChartXFilteredTFWaterfall.AxisX.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredTFWaterfall.AxisX.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisX.MajorGridCount = -1;
            this.easyChartXFilteredTFWaterfall.AxisX.MajorGridEnabled = true;
            this.easyChartXFilteredTFWaterfall.AxisX.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredTFWaterfall.AxisX.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredTFWaterfall.AxisX.Maximum = 1000D;
            this.easyChartXFilteredTFWaterfall.AxisX.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredTFWaterfall.AxisX.Minimum = 1D;
            this.easyChartXFilteredTFWaterfall.AxisX.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredTFWaterfall.AxisX.MinorGridEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisX.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredTFWaterfall.AxisX.ShowLogarithmicLines = false;
            this.easyChartXFilteredTFWaterfall.AxisX.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisX.TickWidth = 1F;
            this.easyChartXFilteredTFWaterfall.AxisX.Title = "";
            this.easyChartXFilteredTFWaterfall.AxisX.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredTFWaterfall.AxisX.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredTFWaterfall.AxisX.ViewMaximum = 1000D;
            this.easyChartXFilteredTFWaterfall.AxisX.ViewMinimum = 0D;
            this.easyChartXFilteredTFWaterfall.AxisX2.AutoScale = true;
            this.easyChartXFilteredTFWaterfall.AxisX2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredTFWaterfall.AxisX2.AutoZoomReset = false;
            this.easyChartXFilteredTFWaterfall.AxisX2.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisX2.InitWithScaleView = false;
            this.easyChartXFilteredTFWaterfall.AxisX2.IsLogarithmic = false;
            this.easyChartXFilteredTFWaterfall.AxisX2.LabelAngle = 0;
            this.easyChartXFilteredTFWaterfall.AxisX2.LabelEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisX2.LabelFormat = null;
            this.easyChartXFilteredTFWaterfall.AxisX2.LogarithmBase = 10D;
            this.easyChartXFilteredTFWaterfall.AxisX2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredTFWaterfall.AxisX2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisX2.MajorGridCount = -1;
            this.easyChartXFilteredTFWaterfall.AxisX2.MajorGridEnabled = true;
            this.easyChartXFilteredTFWaterfall.AxisX2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredTFWaterfall.AxisX2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredTFWaterfall.AxisX2.Maximum = 1000D;
            this.easyChartXFilteredTFWaterfall.AxisX2.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredTFWaterfall.AxisX2.Minimum = 0D;
            this.easyChartXFilteredTFWaterfall.AxisX2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredTFWaterfall.AxisX2.MinorGridEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisX2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredTFWaterfall.AxisX2.ShowLogarithmicLines = false;
            this.easyChartXFilteredTFWaterfall.AxisX2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisX2.TickWidth = 1F;
            this.easyChartXFilteredTFWaterfall.AxisX2.Title = "";
            this.easyChartXFilteredTFWaterfall.AxisX2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredTFWaterfall.AxisX2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredTFWaterfall.AxisX2.ViewMaximum = 1000D;
            this.easyChartXFilteredTFWaterfall.AxisX2.ViewMinimum = 0D;
            this.easyChartXFilteredTFWaterfall.AxisY.AutoScale = true;
            this.easyChartXFilteredTFWaterfall.AxisY.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredTFWaterfall.AxisY.AutoZoomReset = false;
            this.easyChartXFilteredTFWaterfall.AxisY.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisY.InitWithScaleView = false;
            this.easyChartXFilteredTFWaterfall.AxisY.IsLogarithmic = false;
            this.easyChartXFilteredTFWaterfall.AxisY.LabelAngle = 0;
            this.easyChartXFilteredTFWaterfall.AxisY.LabelEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisY.LabelFormat = null;
            this.easyChartXFilteredTFWaterfall.AxisY.LogarithmBase = 10D;
            this.easyChartXFilteredTFWaterfall.AxisY.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredTFWaterfall.AxisY.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisY.MajorGridCount = 6;
            this.easyChartXFilteredTFWaterfall.AxisY.MajorGridEnabled = true;
            this.easyChartXFilteredTFWaterfall.AxisY.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredTFWaterfall.AxisY.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredTFWaterfall.AxisY.Maximum = 3.5D;
            this.easyChartXFilteredTFWaterfall.AxisY.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredTFWaterfall.AxisY.Minimum = 0.5D;
            this.easyChartXFilteredTFWaterfall.AxisY.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredTFWaterfall.AxisY.MinorGridEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisY.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredTFWaterfall.AxisY.ShowLogarithmicLines = false;
            this.easyChartXFilteredTFWaterfall.AxisY.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisY.TickWidth = 1F;
            this.easyChartXFilteredTFWaterfall.AxisY.Title = "";
            this.easyChartXFilteredTFWaterfall.AxisY.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredTFWaterfall.AxisY.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredTFWaterfall.AxisY.ViewMaximum = 3.5D;
            this.easyChartXFilteredTFWaterfall.AxisY.ViewMinimum = 0.5D;
            this.easyChartXFilteredTFWaterfall.AxisY2.AutoScale = true;
            this.easyChartXFilteredTFWaterfall.AxisY2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredTFWaterfall.AxisY2.AutoZoomReset = false;
            this.easyChartXFilteredTFWaterfall.AxisY2.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisY2.InitWithScaleView = false;
            this.easyChartXFilteredTFWaterfall.AxisY2.IsLogarithmic = false;
            this.easyChartXFilteredTFWaterfall.AxisY2.LabelAngle = 0;
            this.easyChartXFilteredTFWaterfall.AxisY2.LabelEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisY2.LabelFormat = null;
            this.easyChartXFilteredTFWaterfall.AxisY2.LogarithmBase = 10D;
            this.easyChartXFilteredTFWaterfall.AxisY2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredTFWaterfall.AxisY2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisY2.MajorGridCount = 6;
            this.easyChartXFilteredTFWaterfall.AxisY2.MajorGridEnabled = true;
            this.easyChartXFilteredTFWaterfall.AxisY2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredTFWaterfall.AxisY2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredTFWaterfall.AxisY2.Maximum = 3.5D;
            this.easyChartXFilteredTFWaterfall.AxisY2.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredTFWaterfall.AxisY2.Minimum = 0.5D;
            this.easyChartXFilteredTFWaterfall.AxisY2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredTFWaterfall.AxisY2.MinorGridEnabled = false;
            this.easyChartXFilteredTFWaterfall.AxisY2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredTFWaterfall.AxisY2.ShowLogarithmicLines = false;
            this.easyChartXFilteredTFWaterfall.AxisY2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.AxisY2.TickWidth = 1F;
            this.easyChartXFilteredTFWaterfall.AxisY2.Title = "";
            this.easyChartXFilteredTFWaterfall.AxisY2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredTFWaterfall.AxisY2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredTFWaterfall.AxisY2.ViewMaximum = 3.5D;
            this.easyChartXFilteredTFWaterfall.AxisY2.ViewMinimum = 0.5D;
            this.easyChartXFilteredTFWaterfall.BackColor = System.Drawing.Color.White;
            this.easyChartXFilteredTFWaterfall.ChartAreaBackColor = System.Drawing.Color.Empty;
            this.easyChartXFilteredTFWaterfall.Cumulitive = false;
            this.easyChartXFilteredTFWaterfall.GradientStyle = SeeSharpTools.JY.GUI.EasyChartX.ChartGradientStyle.None;
            this.easyChartXFilteredTFWaterfall.LegendBackColor = System.Drawing.Color.Transparent;
            this.easyChartXFilteredTFWaterfall.LegendFont = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            this.easyChartXFilteredTFWaterfall.LegendForeColor = System.Drawing.Color.Black;
            this.easyChartXFilteredTFWaterfall.LegendVisible = false;
            easyChartXSeries3.Color = System.Drawing.Color.Red;
            easyChartXSeries3.Marker = SeeSharpTools.JY.GUI.EasyChartXSeries.MarkerType.None;
            easyChartXSeries3.Name = "Series1";
            easyChartXSeries3.Type = SeeSharpTools.JY.GUI.EasyChartXSeries.LineType.FastLine;
            easyChartXSeries3.Visible = true;
            easyChartXSeries3.Width = SeeSharpTools.JY.GUI.EasyChartXSeries.LineWidth.Thin;
            easyChartXSeries3.XPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            easyChartXSeries3.YPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            this.easyChartXFilteredTFWaterfall.LineSeries.Add(easyChartXSeries3);
            this.easyChartXFilteredTFWaterfall.Location = new System.Drawing.Point(1, 216);
            this.easyChartXFilteredTFWaterfall.Miscellaneous.CheckInfinity = false;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.CheckNaN = false;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.CheckNegtiveOrZero = false;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.DataStorage = SeeSharpTools.JY.GUI.DataStorageType.Clone;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.DirectionChartCount = 3;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.Fitting = SeeSharpTools.JY.GUI.EasyChartX.FitType.Range;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.MarkerSize = 7;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.MaxSeriesCount = 32;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.MaxSeriesPointCount = 4000;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.ShowFunctionMenu = true;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.SplitLayoutColumnInterval = 0F;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.SplitLayoutDirection = SeeSharpTools.JY.GUI.EasyChartXUtility.LayoutDirection.LeftToRight;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.SplitLayoutRowInterval = 0F;
            this.easyChartXFilteredTFWaterfall.Miscellaneous.SplitViewAutoLayout = true;
            this.easyChartXFilteredTFWaterfall.Name = "easyChartXFilteredTFWaterfall";
            this.easyChartXFilteredTFWaterfall.SeriesCount = 0;
            this.easyChartXFilteredTFWaterfall.Size = new System.Drawing.Size(352, 178);
            this.easyChartXFilteredTFWaterfall.SplitView = false;
            this.easyChartXFilteredTFWaterfall.TabIndex = 2;
            this.easyChartXFilteredTFWaterfall.XCursor.AutoInterval = true;
            this.easyChartXFilteredTFWaterfall.XCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXFilteredTFWaterfall.XCursor.Interval = 0.001D;
            this.easyChartXFilteredTFWaterfall.XCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Zoom;
            this.easyChartXFilteredTFWaterfall.XCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXFilteredTFWaterfall.XCursor.Value = double.NaN;
            this.easyChartXFilteredTFWaterfall.YCursor.AutoInterval = true;
            this.easyChartXFilteredTFWaterfall.YCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXFilteredTFWaterfall.YCursor.Interval = 0.001D;
            this.easyChartXFilteredTFWaterfall.YCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Disabled;
            this.easyChartXFilteredTFWaterfall.YCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXFilteredTFWaterfall.YCursor.Value = double.NaN;
            // 
            // easyChartXFilteredWaveform
            // 
            this.easyChartXFilteredWaveform.AutoClear = true;
            this.easyChartXFilteredWaveform.AxisX.AutoScale = true;
            this.easyChartXFilteredWaveform.AxisX.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredWaveform.AxisX.AutoZoomReset = false;
            this.easyChartXFilteredWaveform.AxisX.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisX.InitWithScaleView = false;
            this.easyChartXFilteredWaveform.AxisX.IsLogarithmic = false;
            this.easyChartXFilteredWaveform.AxisX.LabelAngle = 0;
            this.easyChartXFilteredWaveform.AxisX.LabelEnabled = true;
            this.easyChartXFilteredWaveform.AxisX.LabelFormat = null;
            this.easyChartXFilteredWaveform.AxisX.LogarithmBase = 10D;
            this.easyChartXFilteredWaveform.AxisX.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredWaveform.AxisX.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisX.MajorGridCount = -1;
            this.easyChartXFilteredWaveform.AxisX.MajorGridEnabled = true;
            this.easyChartXFilteredWaveform.AxisX.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredWaveform.AxisX.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredWaveform.AxisX.Maximum = 1000D;
            this.easyChartXFilteredWaveform.AxisX.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredWaveform.AxisX.Minimum = 0D;
            this.easyChartXFilteredWaveform.AxisX.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredWaveform.AxisX.MinorGridEnabled = false;
            this.easyChartXFilteredWaveform.AxisX.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredWaveform.AxisX.ShowLogarithmicLines = false;
            this.easyChartXFilteredWaveform.AxisX.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisX.TickWidth = 1F;
            this.easyChartXFilteredWaveform.AxisX.Title = "";
            this.easyChartXFilteredWaveform.AxisX.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredWaveform.AxisX.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredWaveform.AxisX.ViewMaximum = 1000D;
            this.easyChartXFilteredWaveform.AxisX.ViewMinimum = 0D;
            this.easyChartXFilteredWaveform.AxisX2.AutoScale = true;
            this.easyChartXFilteredWaveform.AxisX2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredWaveform.AxisX2.AutoZoomReset = false;
            this.easyChartXFilteredWaveform.AxisX2.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisX2.InitWithScaleView = false;
            this.easyChartXFilteredWaveform.AxisX2.IsLogarithmic = false;
            this.easyChartXFilteredWaveform.AxisX2.LabelAngle = 0;
            this.easyChartXFilteredWaveform.AxisX2.LabelEnabled = true;
            this.easyChartXFilteredWaveform.AxisX2.LabelFormat = null;
            this.easyChartXFilteredWaveform.AxisX2.LogarithmBase = 10D;
            this.easyChartXFilteredWaveform.AxisX2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredWaveform.AxisX2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisX2.MajorGridCount = -1;
            this.easyChartXFilteredWaveform.AxisX2.MajorGridEnabled = true;
            this.easyChartXFilteredWaveform.AxisX2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredWaveform.AxisX2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredWaveform.AxisX2.Maximum = 1000D;
            this.easyChartXFilteredWaveform.AxisX2.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredWaveform.AxisX2.Minimum = 0D;
            this.easyChartXFilteredWaveform.AxisX2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredWaveform.AxisX2.MinorGridEnabled = false;
            this.easyChartXFilteredWaveform.AxisX2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredWaveform.AxisX2.ShowLogarithmicLines = false;
            this.easyChartXFilteredWaveform.AxisX2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisX2.TickWidth = 1F;
            this.easyChartXFilteredWaveform.AxisX2.Title = "";
            this.easyChartXFilteredWaveform.AxisX2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredWaveform.AxisX2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredWaveform.AxisX2.ViewMaximum = 1000D;
            this.easyChartXFilteredWaveform.AxisX2.ViewMinimum = 0D;
            this.easyChartXFilteredWaveform.AxisY.AutoScale = false;
            this.easyChartXFilteredWaveform.AxisY.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredWaveform.AxisY.AutoZoomReset = false;
            this.easyChartXFilteredWaveform.AxisY.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisY.InitWithScaleView = false;
            this.easyChartXFilteredWaveform.AxisY.IsLogarithmic = false;
            this.easyChartXFilteredWaveform.AxisY.LabelAngle = 0;
            this.easyChartXFilteredWaveform.AxisY.LabelEnabled = true;
            this.easyChartXFilteredWaveform.AxisY.LabelFormat = null;
            this.easyChartXFilteredWaveform.AxisY.LogarithmBase = 10D;
            this.easyChartXFilteredWaveform.AxisY.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredWaveform.AxisY.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisY.MajorGridCount = 6;
            this.easyChartXFilteredWaveform.AxisY.MajorGridEnabled = true;
            this.easyChartXFilteredWaveform.AxisY.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredWaveform.AxisY.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredWaveform.AxisY.Maximum = 3.5D;
            this.easyChartXFilteredWaveform.AxisY.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredWaveform.AxisY.Minimum = -3.5D;
            this.easyChartXFilteredWaveform.AxisY.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredWaveform.AxisY.MinorGridEnabled = false;
            this.easyChartXFilteredWaveform.AxisY.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredWaveform.AxisY.ShowLogarithmicLines = false;
            this.easyChartXFilteredWaveform.AxisY.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisY.TickWidth = 1F;
            this.easyChartXFilteredWaveform.AxisY.Title = "";
            this.easyChartXFilteredWaveform.AxisY.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredWaveform.AxisY.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredWaveform.AxisY.ViewMaximum = 3.5D;
            this.easyChartXFilteredWaveform.AxisY.ViewMinimum = 0.5D;
            this.easyChartXFilteredWaveform.AxisY2.AutoScale = true;
            this.easyChartXFilteredWaveform.AxisY2.AutoScalingMode = SeeSharpTools.JY.GUI.EasyChartXAxis.AutoScaleMode.ByGridCount;
            this.easyChartXFilteredWaveform.AxisY2.AutoZoomReset = false;
            this.easyChartXFilteredWaveform.AxisY2.Color = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisY2.InitWithScaleView = false;
            this.easyChartXFilteredWaveform.AxisY2.IsLogarithmic = false;
            this.easyChartXFilteredWaveform.AxisY2.LabelAngle = 0;
            this.easyChartXFilteredWaveform.AxisY2.LabelEnabled = true;
            this.easyChartXFilteredWaveform.AxisY2.LabelFormat = null;
            this.easyChartXFilteredWaveform.AxisY2.LogarithmBase = 10D;
            this.easyChartXFilteredWaveform.AxisY2.LogLabelStyle = SeeSharpTools.JY.GUI.EasyChartXAxis.LogarithmicLabelStyle.E2;
            this.easyChartXFilteredWaveform.AxisY2.MajorGridColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisY2.MajorGridCount = 6;
            this.easyChartXFilteredWaveform.AxisY2.MajorGridEnabled = true;
            this.easyChartXFilteredWaveform.AxisY2.MajorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.Dash;
            this.easyChartXFilteredWaveform.AxisY2.MaxGridCountPerPixel = 0.012D;
            this.easyChartXFilteredWaveform.AxisY2.Maximum = 3.5D;
            this.easyChartXFilteredWaveform.AxisY2.MinGridCountPerPixel = 0.004D;
            this.easyChartXFilteredWaveform.AxisY2.Minimum = 0.5D;
            this.easyChartXFilteredWaveform.AxisY2.MinorGridColor = System.Drawing.Color.DimGray;
            this.easyChartXFilteredWaveform.AxisY2.MinorGridEnabled = false;
            this.easyChartXFilteredWaveform.AxisY2.MinorGridType = SeeSharpTools.JY.GUI.EasyChartXAxis.GridStyle.DashDot;
            this.easyChartXFilteredWaveform.AxisY2.ShowLogarithmicLines = false;
            this.easyChartXFilteredWaveform.AxisY2.TickLineColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.AxisY2.TickWidth = 1F;
            this.easyChartXFilteredWaveform.AxisY2.Title = "";
            this.easyChartXFilteredWaveform.AxisY2.TitleOrientation = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextOrientation.Auto;
            this.easyChartXFilteredWaveform.AxisY2.TitlePosition = SeeSharpTools.JY.GUI.EasyChartXAxis.AxisTextPosition.Center;
            this.easyChartXFilteredWaveform.AxisY2.ViewMaximum = 3.5D;
            this.easyChartXFilteredWaveform.AxisY2.ViewMinimum = 0.5D;
            this.easyChartXFilteredWaveform.BackColor = System.Drawing.Color.White;
            this.easyChartXFilteredWaveform.ChartAreaBackColor = System.Drawing.Color.Empty;
            this.easyChartXFilteredWaveform.Cumulitive = false;
            this.easyChartXFilteredWaveform.GradientStyle = SeeSharpTools.JY.GUI.EasyChartX.ChartGradientStyle.None;
            this.easyChartXFilteredWaveform.LegendBackColor = System.Drawing.Color.Transparent;
            this.easyChartXFilteredWaveform.LegendFont = new System.Drawing.Font("Microsoft Sans Serif", 8F);
            this.easyChartXFilteredWaveform.LegendForeColor = System.Drawing.Color.Black;
            this.easyChartXFilteredWaveform.LegendVisible = false;
            easyChartXSeries4.Color = System.Drawing.Color.Red;
            easyChartXSeries4.Marker = SeeSharpTools.JY.GUI.EasyChartXSeries.MarkerType.None;
            easyChartXSeries4.Name = "Series1";
            easyChartXSeries4.Type = SeeSharpTools.JY.GUI.EasyChartXSeries.LineType.FastLine;
            easyChartXSeries4.Visible = true;
            easyChartXSeries4.Width = SeeSharpTools.JY.GUI.EasyChartXSeries.LineWidth.Thin;
            easyChartXSeries4.XPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            easyChartXSeries4.YPlotAxis = SeeSharpTools.JY.GUI.EasyChartXAxis.PlotAxis.Primary;
            this.easyChartXFilteredWaveform.LineSeries.Add(easyChartXSeries4);
            this.easyChartXFilteredWaveform.Location = new System.Drawing.Point(352, 216);
            this.easyChartXFilteredWaveform.Miscellaneous.CheckInfinity = false;
            this.easyChartXFilteredWaveform.Miscellaneous.CheckNaN = false;
            this.easyChartXFilteredWaveform.Miscellaneous.CheckNegtiveOrZero = false;
            this.easyChartXFilteredWaveform.Miscellaneous.DataStorage = SeeSharpTools.JY.GUI.DataStorageType.Clone;
            this.easyChartXFilteredWaveform.Miscellaneous.DirectionChartCount = 3;
            this.easyChartXFilteredWaveform.Miscellaneous.Fitting = SeeSharpTools.JY.GUI.EasyChartX.FitType.Range;
            this.easyChartXFilteredWaveform.Miscellaneous.MarkerSize = 7;
            this.easyChartXFilteredWaveform.Miscellaneous.MaxSeriesCount = 32;
            this.easyChartXFilteredWaveform.Miscellaneous.MaxSeriesPointCount = 4000;
            this.easyChartXFilteredWaveform.Miscellaneous.ShowFunctionMenu = true;
            this.easyChartXFilteredWaveform.Miscellaneous.SplitLayoutColumnInterval = 0F;
            this.easyChartXFilteredWaveform.Miscellaneous.SplitLayoutDirection = SeeSharpTools.JY.GUI.EasyChartXUtility.LayoutDirection.LeftToRight;
            this.easyChartXFilteredWaveform.Miscellaneous.SplitLayoutRowInterval = 0F;
            this.easyChartXFilteredWaveform.Miscellaneous.SplitViewAutoLayout = true;
            this.easyChartXFilteredWaveform.Name = "easyChartXFilteredWaveform";
            this.easyChartXFilteredWaveform.SeriesCount = 0;
            this.easyChartXFilteredWaveform.Size = new System.Drawing.Size(352, 178);
            this.easyChartXFilteredWaveform.SplitView = false;
            this.easyChartXFilteredWaveform.TabIndex = 3;
            this.easyChartXFilteredWaveform.XCursor.AutoInterval = true;
            this.easyChartXFilteredWaveform.XCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXFilteredWaveform.XCursor.Interval = 0.001D;
            this.easyChartXFilteredWaveform.XCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Zoom;
            this.easyChartXFilteredWaveform.XCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXFilteredWaveform.XCursor.Value = double.NaN;
            this.easyChartXFilteredWaveform.YCursor.AutoInterval = true;
            this.easyChartXFilteredWaveform.YCursor.Color = System.Drawing.Color.DeepSkyBlue;
            this.easyChartXFilteredWaveform.YCursor.Interval = 0.001D;
            this.easyChartXFilteredWaveform.YCursor.Mode = SeeSharpTools.JY.GUI.EasyChartXCursor.CursorMode.Disabled;
            this.easyChartXFilteredWaveform.YCursor.SelectionColor = System.Drawing.Color.LightGray;
            this.easyChartXFilteredWaveform.YCursor.Value = double.NaN;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.radioButtonHalfSpectrum);
            this.groupBox1.Controls.Add(this.radioButtonFullSpectrum);
            this.groupBox1.ImeMode = System.Windows.Forms.ImeMode.Disable;
            this.groupBox1.Location = new System.Drawing.Point(709, 18);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(2);
            this.groupBox1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.groupBox1.Size = new System.Drawing.Size(117, 62);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Settings";
            // 
            // radioButtonHalfSpectrum
            // 
            this.radioButtonHalfSpectrum.AutoSize = true;
            this.radioButtonHalfSpectrum.Checked = true;
            this.radioButtonHalfSpectrum.Location = new System.Drawing.Point(4, 43);
            this.radioButtonHalfSpectrum.Margin = new System.Windows.Forms.Padding(2);
            this.radioButtonHalfSpectrum.Name = "radioButtonHalfSpectrum";
            this.radioButtonHalfSpectrum.Size = new System.Drawing.Size(101, 16);
            this.radioButtonHalfSpectrum.TabIndex = 13;
            this.radioButtonHalfSpectrum.TabStop = true;
            this.radioButtonHalfSpectrum.Text = "Half Spectrum";
            this.radioButtonHalfSpectrum.UseVisualStyleBackColor = true;
            // 
            // radioButtonFullSpectrum
            // 
            this.radioButtonFullSpectrum.AutoSize = true;
            this.radioButtonFullSpectrum.Location = new System.Drawing.Point(4, 23);
            this.radioButtonFullSpectrum.Margin = new System.Windows.Forms.Padding(2);
            this.radioButtonFullSpectrum.Name = "radioButtonFullSpectrum";
            this.radioButtonFullSpectrum.Size = new System.Drawing.Size(101, 16);
            this.radioButtonFullSpectrum.TabIndex = 12;
            this.radioButtonFullSpectrum.Text = "Full Spectrum";
            this.radioButtonFullSpectrum.UseVisualStyleBackColor = true;
            // 
            // easyButtonGo
            // 
            this.easyButtonGo.BackgroundStyle = SeeSharpTools.JY.GUI.BackgroundStyle.Normal;
            this.easyButtonGo.BorderColor = System.Drawing.Color.Silver;
            this.easyButtonGo.BorderRadius = 20;
            this.easyButtonGo.BorderThickness = 1;
            this.easyButtonGo.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(180)))), ((int)(((byte)(205)))));
            this.easyButtonGo.ButtonColor2 = System.Drawing.Color.Silver;
            this.easyButtonGo.ButtonImage = null;
            this.easyButtonGo.Image = null;
            this.easyButtonGo.ImageSize = new System.Drawing.Size(0, 0);
            this.easyButtonGo.ImageStretch = false;
            this.easyButtonGo.Location = new System.Drawing.Point(713, 216);
            this.easyButtonGo.Margin = new System.Windows.Forms.Padding(2);
            this.easyButtonGo.Name = "easyButtonGo";
            this.easyButtonGo.PreSetImage = SeeSharpTools.JY.GUI.EasyButton.ButtonPresetImage.None;
            this.easyButtonGo.Shadow = true;
            this.easyButtonGo.Size = new System.Drawing.Size(60, 24);
            this.easyButtonGo.TabIndex = 4;
            this.easyButtonGo.Text = "GO";
            this.easyButtonGo.ThreeDimensional = false;
            this.easyButtonGo.Click += new System.EventHandler(this.easyButton1_Click);
            // 
            // numericUpDownNoiseRMS
            // 
            this.numericUpDownNoiseRMS.DecimalPlaces = 1;
            this.numericUpDownNoiseRMS.Increment = new decimal(new int[] {
            1,
            0,
            0,
            65536});
            this.numericUpDownNoiseRMS.Location = new System.Drawing.Point(713, 106);
            this.numericUpDownNoiseRMS.Margin = new System.Windows.Forms.Padding(2);
            this.numericUpDownNoiseRMS.Name = "numericUpDownNoiseRMS";
            this.numericUpDownNoiseRMS.Size = new System.Drawing.Size(88, 21);
            this.numericUpDownNoiseRMS.TabIndex = 6;
            this.numericUpDownNoiseRMS.Value = new decimal(new int[] {
            5,
            0,
            0,
            65536});
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(711, 92);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(119, 12);
            this.label2.TabIndex = 7;
            this.label2.Text = "Noise RMS Amplitude";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(3, 4);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(215, 12);
            this.label3.TabIndex = 8;
            this.label3.Text = "Input Waveform (noisy linear chirp)";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(358, 7);
            this.label4.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(185, 12);
            this.label4.TabIndex = 9;
            this.label4.Text = "Input Time-Frequency Waterfall";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(3, 202);
            this.label5.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(203, 12);
            this.label5.TabIndex = 10;
            this.label5.Text = "Filtered Time-Frequency Waterfall";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(358, 202);
            this.label6.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(107, 12);
            this.label6.TabIndex = 11;
            this.label6.Text = "Filtered Waveform";
            // 
            // FormGaborTransformExample
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(848, 406);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.numericUpDownNoiseRMS);
            this.Controls.Add(this.easyButtonGo);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.easyChartXFilteredWaveform);
            this.Controls.Add(this.easyChartXFilteredTFWaterfall);
            this.Controls.Add(this.easyChartXInputTFWaterfall);
            this.Controls.Add(this.easyChartXInputWaveform);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "FormGaborTransformExample";
            this.Text = "Gabor Transform Example";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownNoiseRMS)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private SeeSharpTools.JY.GUI.EasyChartX easyChartXInputWaveform;
        private SeeSharpTools.JY.GUI.EasyChartX easyChartXInputTFWaterfall;
        private SeeSharpTools.JY.GUI.EasyChartX easyChartXFilteredTFWaterfall;
        private SeeSharpTools.JY.GUI.EasyChartX easyChartXFilteredWaveform;
        private System.Windows.Forms.GroupBox groupBox1;
        private SeeSharpTools.JY.GUI.EasyButton easyButtonGo;
        private System.Windows.Forms.NumericUpDown numericUpDownNoiseRMS;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.RadioButton radioButtonFullSpectrum;
        private System.Windows.Forms.RadioButton radioButtonHalfSpectrum;
    }
}

